name: Translate MRAs

on:
  schedule:
    - cron:  '23 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Translate MRAs
      run: |
        set -euo pipefail
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"
        ./.github/translate_mras.py
      env:
        REPOSITORY_DISPATCH_THEYPSILON: ${{ secrets.REPOSITORY_DISPATCH_THEYPSILON }}
